import React, { Component } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Header from './components/header/Header';

class index extends Component {
  render() {
    return (
      <div >
        <Head>
          <title>Resume | Kazi Rayhan</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main className={styles.container}>
          <h2>Kazi Rayhan</h2>
        </main>

        <footer className={styles.footer}>
        </footer>
      </div>
    );
  }
}

export default index;
